apiVersion: apps/v1
kind: Deployment
metadata:
  name: hilltop-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: hilltop-container
        image: hilltopconsultancy/nodejs-app:v1
        ports:
        - containerPort: 8080
