kind: Service
apiVersion: v1
metadata:
  name:  hilltop-np-svc
spec:
  selector:
    app:  myapp
  type: NodePort
  ports:
  - protocol:  TCP
    port:  80
    targetPort:  8080
    nodePort: 30007