apiVersion: v1
kind: Service
metadata:
  name: hilltop-svc
spec:
  selector:
    app: nodejs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30035
  type: NodePort
